apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${K8S_CLUSTER_CA_DATA}
    server: ${K8S_CLUSTER_SERVER}
  name: ${K8S_CLUSTER_NAME}
contexts:
- context:
    cluster: ${K8S_CLUSTER_NAME}
    user: ${K8S_USER_NAME}
  name: ${K8S_CLUSTER_NAME}
current-context: ${K8S_CLUSTER_NAME}
kind: Config
preferences: {}
users:
- name: ${K8S_USER_NAME}
  user:
    token: ${DIGITALOCEAN_TOKEN} 