apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEV3TVRneQpNRFUxTVRKYUZ3MDBOVEV3TVRneU1EVTFNVEphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDcTl6SzJhZlhRR0VFd0lkNFlEcXNMbjFXUFdlQVZzOHdRYlpGY0I0MXg2QkhqL3lOVwptRUJIR1JLK2ZNQklmYzl1cmlXSGZ3NUJITk54d1lTODlia2t3akFaRE4vUFFEN1JiMVlsYTc4NVI4QnhFS2M0CnV0cjNrcDljVDhIQk5icWQzVW5vZ1NpS0NuOUxsZWZ3cXFyamxjZW8vcm8ydFdrTEtSN3dadzVlYmliUy91YlQKcGtwcFF6c1VOS095SUw2OTBYOWlDaHUrdVJRWUFpcnpVbE9sc090RnJIL3p4cExPVEl0VXdTQjhHb3NCYnZjbwp3SFU4bVpXdHJOZkk3aVpIZTNGZ0VqMUpGZG1IbmNxZ2xxQlNId1EreWlNYU1yZGpkTW1oRm1nak9QWlhGTTZuCkZrcDhjc0s0WEZaN2p3ZE0rcFY5NlRWYUFKWmpPY3k3UXcyN0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRSci9yczlBdENTMElrREMrMQo1QzBNTjRHdXNEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNZ0czaGdGRjZOSXRtUXd1U3lOVXZLbzdBeXB2ClNwTU9WQzJHZEdZd2g0QXhKelNYRmVSWUxpclQ2NlFuOVhYRHBvZElKbkVhTHVUcnJ0MXNSKzFocndxSEJRSlAKNGp5NnhQcUd6ZDd2Mm1XUlNDenUwaElocVo1czg1T1RKSFhIcHExSSs1bXhneHMvODAwUHBNVUFGZTNETE44RwpJOU5CUHRObHdjN0p3dmRqZnBDNTk3dEZrUFluSGVJUWZqRFdRb3RyRDY2WjE4bnBZK1pWcXJObkdpemt1R1BnCmpvbjRSTXdNMDU1SDRMQmVsZlV5ZXZmWVFjTFAwOFlRTE40aDR4TEFTcjBpMm5TRlZVTkh1dVhyTzVJaGoydzgKYnpRSGFDYTdsN3pQTHdpUmthQjNwbFJ3NXpOWFQyT1Vsc01yZSsrL3FuU1RsZ1g1bVdnVjdWUi9EZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://36a16fa8-6183-464a-bc42-0f04386242dd.k8s.ondigitalocean.com
  name: do-nyc1-k8s-inf326-nyc1
contexts:
- context:
    cluster: do-nyc1-k8s-inf326-nyc1
    user: do-nyc1-k8s-inf326-nyc1-admin
  name: do-nyc1-k8s-inf326-nyc1
current-context: do-nyc1-k8s-inf326-nyc1
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-inf326-nyc1-admin
  user:
    token: ${{ secrets.DIGITALOCEAN_TOKEN }}
