apiVersion: v1
kind: ConfigMap
metadata:
  name: file-service-config
  namespace: file-service
data:
  APP_NAME: "servicio-archivos"
  APP_ENV: "production"
  APP_PORT: "8080"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "filesvc"
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_SECURE: "0"
  MINIO_BUCKET: "files"
  PUBLIC_MINIO_URL: "http://minio-service:9000"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_EXCHANGE: "files"
