apiVersion: v1
kind: Secret
metadata:
  name: file-service-secrets
  namespace: file-service
type: Opaque
stringData:
  POSTGRES_USER: "filesvc"
  POSTGRES_PASSWORD: "filesvc_prod_2025"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin_prod_2025"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
